FACK1/M-E-Platform

package.json, src/controllers/activity.controller.js, src/models/Activity.js, src/router.js
=> get all activites

src/app.js, src/router.js
React app runs from the express server (using build directory).
=> Fix react run issue

client/package-lock.json, client/package.json, client/src/components/Table/index.js, client/src/components/pages/ViewActivities/index.js, client/src/components/pages/ViewActivities/index.style.js, package-lock.json, src/controllers/activity.controller.js
=>  Make table-component 

client/package-lock.json, client/src/App.js, client/src/components/ActivityDetails/index.js, client/src/components/ActivityDetails/index.style.js, client/src/components/Form/index.js, client/src/components/pages/ActivityInformation/index.js, client/src/components/pages/ActivityInformation/index.style.js, client/src/components/pages/ViewActivities/index.js, package-lock.json, src/controllers/activity.controller.js, src/models/Activity.js, src/router.js
=> Activity information

client/src/components/pages/ActivityInformation/index.js, client/src/components/pages/ActivityInformation/index.style.js
=> Add table to one activity information page #2 fixed #51

client/src/components/pages/ViewUsers/index.js, src/controllers/user.controller.js, src/router.js
=> View users  #7 fixed #57 

client/package-lock.json, client/package.json, client/src/components/pages/ViewActivities/index.js, package-lock.json, package.json
fixes #46
by using react cell to control one cell from the table.
=> Activity details

client/package-lock.json, client/package.json, client/src/components/pages/ViewActivities/index.js, package-lock.json, package.json
=> Revert "Activity details"

client/src/App.js, client/src/components/Header/index.js, client/src/components/pages/ViewPrograms/index.js, client/src/components/pages/ViewPrograms/index.style.js, src/controllers/activity.controller.js, src/controllers/program.controller.js, src/router.js
=> View programs

client/src/App.js, client/src/components/ProgramDetails/index.js, client/src/components/ProgramDetails/index.style.js, client/src/components/pages/ProgramInformation/index.js, client/src/components/pages/ProgramInformation/index.style.js, src/controllers/program.controller.js, src/router.js
=> Program information

client/package-lock.json, client/src/components/pages/CreateActivity/index.js, src/controllers/index.js, src/controllers/objective.controller.js, src/router.js
=> fix program and objective in add activity #10 

client/src/components/pages/ActivityInformation/index.js, src/controllers/activity.controller.js, src/controllers/user.controller.js, src/models/ActivitiesUser.js, src/mongoose.config.js, src/router.js
=> Add user to activity #12 fixed #58

package-lock.json, package.json, src/router.js, src/validations/index.js, src/validations/user.validate.js, src/validations/validation.js
=> Server validation 

client/src/components/pages/ViewActivities/index.js, client/src/components/pages/ViewUsers/index.js
=> change date from timestamp to date fixed  #53

client/src/components/pages/ProgramInformation/index.js, src/controllers/activity.controller.js, src/router.js
=> Program details

client/src/components/Form/index.js, client/src/components/pages/CreateActivity/index.js
=> Form initial values

client/src/components/Form/index.js, client/src/components/Form/index.style.js, client/src/components/pages/CreateActivity/index.js, client/src/components/pages/CreateProgram/index.js, client/src/components/pages/CreateUser/index.js, src/controllers/user.controller.js, src/validations/user.validate.js
=> Fix buttons response

package-lock.json, package.json, src/controllers/auth.controller.js, src/controllers/index.js, src/models/User.js, src/router.js
=> Server Authentication

client/src/components/pages/ActivityInformation/index.js, src/controllers/auth.controller.js, src/controllers/user.controller.js, src/models/ActivitiesUser.js, src/models/User.js, src/router.js
=> Fix activity multi add fixed #93 #94

client/public/index.html
Just update the title of the App.
=> Update the title of the app #100

README.md
=> WIP: Update readme
